apiVersion: v1
kind: Service
metadata:
  name: geoapi-service
  labels:
    app: geoapi
    component: backend
spec:
  type: ClusterIP
  selector:
    app: geoapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: None
